// react/src/components/UrlTrimComponent.tsx
import { inject, observer } from 'mobx-react';
import React from 'react';
import { Link } from 'react-router-dom';
import { trimUrlApi } from '../api';
import { IStore, Store } from '../state';

@inject('urlTrim')
@observer
export class UrlTrimComponent extends
	React.Component<IStore>
{
	textChange(
		text: string,
	) {
		Store.urlTrim.setTrim('');
		if (!(
			text &&
			text.trim()
		)) {
			text = '';
		}
		Store.urlTrim.setText(text);
	}
	onReset() {
		Store.ajax.init();
		Store.urlTrim.setText('');
		this.forceUpdate();
	}
	render() {
		const p = this.props.urlTrim;
		if (!p) {
			return null;
		}
		const api = trimUrlApi(Store);
		return (
			<div
				className='urlTrim'
			>
				<input
					type='text'
					placeholder={p.labels[0]}
					value={p.text}
					onChange={(e) => this.textChange(e.target.value)}
					disabled={p.disableEdit}
					title={p.labels[1].toUpperCase()}
				/>
				<button
					type='submit'
					onClick={() => api.trimUriAsync()}
					disabled={p.disableTrim}
				>
					Trim
				</button>
				{p.showTrim && (
					<Link
						to={p.trim}
					>
						{p.trim}
					</Link>
				)}
				{p.showTrim && (
					<button
						onClick={() => this.onReset()}
					>
						Clear
					</button>
				)}
			</div>
		);
	}
}

// vue/src/components/UrlTrimComponent.vue
<template>
	<div
		class='urlTrim'
	>
		<input
			type='text'
			:placeholder="p.labels[0]"
			:value='p.text'
			:disabled='p.disableEdit'
			:title='p.labels[1].toUpperCase()'
			@input='textChange'
		/>
		<button
			type='submit'
			:disabled='p.disableTrim'
			@click='trimAsync'
		>
			Trim
		</button>
		<a
			v-if='p.showTrim'
			:href='p.trim'
		>
			{{ p.trim }}
		</a>
		<button
			v-if='p.showTrim'
			@click='onReset'
		>
			Clear
		</button>
	</div>
</template>

<script lang='ts'>
	import { Vue, Component, Prop } from 'vue-property-decorator';
	import { trimUrlApi } from '../api';
	import { IStoreBind, Store, ajaxStateEnum, IUrlTrimState } from '../state';
	import { log } from '../utils';
	import { Observer } from 'mobx-vue';
	import { toJS, action } from 'mobx';

	@Observer
	@Component
	export default class UrlTrimComponent
		extends Vue
	{
		name = 'UrlTrimComponent'
		get p() {
			const s = (this as any).$store as IStoreBind;
			return s.urlTrim;
		};
		onReset() {
			Store.ajax.init();
			const s = (this as any).$store as IStoreBind;
			s.urlTrim.setText('');
		};
		async trimAsync() {
			const s = (this as any).$store as IStoreBind;
			const api = trimUrlApi(s);
			await api.trimUriAsync();
		};
		textChange(
			e: any,
		) {
			let text = e.target.value;
			if (!text.trim()) {
				text = '';
			}
			Store.urlTrim.setText(text);
		};
	}

</script>
