// react/src/components/controls/AjaxState.tsx
import { inject, observer } from 'mobx-react';
import React from 'react';
import { IStore } from '../../state';

@inject('ajax')
@observer
export class AjaxState extends
	React.Component<IStore>
{
	render() {
		const p = this.props.ajax;
		if (!p) {
			return null;
		}
		return (
			<div
				className={p.rootName}
			>
				{p.shouldRender && (
					<div className='blur' />
				)}
				{p.shouldRender && (
					<div
						className={p.className}
					>
						<div>
							{p.state}
						</div>
						{p.hasError && (
							<div>
								{p.error}
							</div>
						)}
					</div>
				)}
			</div>
		);
	}
}

// vue/src/controls/AjaxState.vue
<template>
	<div
		:class='p.rootName'
	>
		<div
			class='blur'
		/>
		<div
			:class='p.className'
			v-if='p.shouldRender'
		>
			<div>
				{{p.state}}
			</div>
			<div
				v-if='p.hasError'
			>
				{{p.error}}
			</div>
		</div>
	</div>
</template>

<script lang='ts' >
	import { Vue, Component } from 'vue-property-decorator';
	import { Observer } from 'mobx-vue';
	import { Store } from '../state';
	
	@Observer
	@Component
	export default class AjaxState
		extends Vue
	{
		name = 'AjaxState'
		p = Store.ajax;
	}

</script>
