// react/src/components/controls/PagingSize.tsx
﻿import { inject, observer } from 'mobx-react';
import React from 'react';
import { IStore, Store } from '../../state';
import { Button } from '../controls';
import { trimUrlApi } from '../../api';

@inject('urlView')
@observer
export class PagingSize extends
	React.Component<IStore>
{
	print(
		v: number
	) {
		let x = v.toString();
		if (x.length < 2) {
			x += '0' + x;
		}
		return x;
	}
	toolTip(
		v: number
	) {
		return this.print(v) + ' items per page';
	}
	render() {
		const p = this.props.urlView;
		if (!p) {
			return null;
		}
		const api = trimUrlApi(Store);
		return (
			<div
				className='pagingSize'
			>
				<span>
					Size
				</span>
				{p.pagingSizes.map((x, i) => {
					return (
						<Button
							key={i}
							toolTip={this.toolTip(x)}
							disabled={x === p.perPage}
							onClick={() => p.setPerPage(api, true, x)}
						>
							{x}
						</Button>
					);
				})}
			</div>
		);
	}
}

// vue/src/controls/PagingSize.vue
﻿<template>
	<div
		class='pagingSize'
	>
		<span>
			Size
		</span>
		<Button
			v-for='x in p.pagingSizes'
			:key='x'
			:disabled='x === p.perPage'
			:onClick='() => onChange(x)'
			:toolTip='print(x) + " items per page"'
		>
			{{print(x)}}
		</Button>
	</div>
</template>

<script lang='ts' >
	import { Vue, Component } from 'vue-property-decorator';
	import { Store } from '../state';
	import Button from './Button.vue';
  	import { Observer } from 'mobx-vue';
	import { trimUrlApi } from '../api';

	@Observer
	@Component({
		components: {
			Button,
		}
	})
	export default class PagingSize
		extends Vue
	{
		name = 'PagingSize';
		get p() {
			return Store.urlView;
		};
		onChange(
			v: number,
		) {
			const api = trimUrlApi(Store);
			Store.urlView.setPerPage(api, true, v);
		};
		print(
			v: number,
		) {
			return (v.toString().length < 2 ? "0" : "") + v;
		};
	}

</script>
