// react/src/components/controls/PagingStyle.tsx
﻿import { inject, observer } from 'mobx-react';
import React from 'react';
import { IStore } from '../../state';
import { OverlayButton } from './OverlayButton';

@inject('urlView')
@observer
export class PagingStyle extends
	React.Component<IStore>
{
	render() {
		const p = this.props.urlView;
		if (!p) {
			return null;
		}
		return (
			<div
				className='pagingStyle'
			>
				<span>
					Style
				</span>
				{p.styleNames.map((x, i) => (
					<OverlayButton
						key={x}
						disabled={x === p.style}
						toolTip={x + ' View'}
						icon={p.styleIcons[i]}
						onClick={() => p.setStyle(x)}
					/>
				))}
			</div>
		);
	}
}

// vue/src/controls/PagingStyle.vue
﻿<template>
	<div
		class='pagingStyle'
	>
		<span>
			Style
		</span>
		<OverlayButton
			v-for='(x, i) in p.styleNames'
			:key='x'
			:disabled='x === p.style'
			:toolTip='x + " view"'
			:icon='p.styleIcons[i]'
			:onClick='() => onChange(x)'
		/>
	</div>
</template>

<script lang='ts' >
	import { Vue, Component } from 'vue-property-decorator';
	import { viewStyleEnum, Store } from '../state';
	import OverlayButton from './OverlayButton.vue';
	import { Observer } from 'mobx-vue';

	@Observer
	@Component({
		components: {
			OverlayButton,
		}
	})
	export default class PagingStyle
		extends Vue
	{
		name = 'PagingStyle';
		get p() {
			return Store.urlView;
		};
		onChange(
			v: viewStyleEnum,
		) {
			Store.urlView.setStyle(v);
		};
	}

</script>
