// react/src/components/urlView/UrlViewGrid.tsx
import React from 'react';
import { IUrlViewModel, Store } from '../../state';

export const UrlViewGrid = (v: IUrlViewModel[]) => (
	<div
		className='urlViewGrid'
	>
		{v.map((x, i) => (
			<div
				key={i}
			>
				<div
					className='urlViewLabel'
				>
					{Store.urlView.viewKeys[0]}
				</div>
				<input
					type='text'
					readOnly={true}
					value={x.address}
				/>
				<div
					className='urlViewLabel'
				>
					{Store.urlView.viewKeys[1]}
				</div>
				<a
					className='urlViewLink'
					href={x.trimmed}
				>
					{x.trimmed}
				</a>
			</div>
		))}
	</div>
);

// vue/src/controls/templates/UrlViewGrid.vue
<template>
	<div
		v-if='p.isGrid'
		class='urlViewGrid'
	>
		<div
			v-for='(x, i) in p.list'
			:key='i'
		>
			<div
				class='urlViewLabel'
			>
				{{p.viewKeys[0]}}
			</div>
			<input
				type='text'
				readOnly='true'
				:value='x.address'
			/>
			<div
				class='urlViewLabel'
			>
				{{p.viewKeys[1]}}
			</div>
			<a
				class='urlViewLink'
				:href='x.trimmed'
			>
				{{x.trimmed}}
			</a>
		</div>
	</div>
</template>

<script lang='ts' >
	import { Vue, Component } from 'vue-property-decorator';
	import { Store } from '../../state';
	import { Observer } from 'mobx-vue';

	@Observer
	@Component
	export default class UriViewGrid
		extends Vue
	{
		name = 'UriViewGrid';
		p = Store.urlView;
	}
</script>
