// vue/src/controls/OverlayButton.vue
﻿<template>
	<button
		:title="toolTip"
		:disabled="disabled"
		:class="className"
        @click="onClick()"
	>
		<Overlay
			:icon="icon"
			:size="size"
		/>
	</button>
</template>

<script lang='ts' >
	import { Vue, Component, Prop } from 'vue-property-decorator';
	import { IButtonProps } from './Button.vue';
	import Overlay, { IOverlayProps } from './Overlay.vue';
	import { overlayIconEnum, overlaySizeEnum } from '../utils';

	interface IProps extends
		IButtonProps,
		IOverlayProps
	{

	}

	@Component({
		components: {
			Overlay,
		}
	})
	export default class OverlayButton
		extends Vue
		implements IProps
	{
		name = 'OverlayButton';
		@Prop({ required: true })
		icon!: overlayIconEnum;
		@Prop()
		size: overlaySizeEnum | undefined;
		@Prop()
		className: string | undefined;
		@Prop({ required: true })
		toolTip!: string;
		@Prop()
		disabled: boolean | undefined;
		@Prop({ required: true })
		onClick!: any;
		get renderClassName() {
			let n = [];
			if (this.className) {
				n.push(this.className);
			}
			if (this.disabled) {
				n.push('disabled');
			}
			return n.join(' ');
		}
	};
</script>

// react/src/components/controls/OverlayButton.tsx
﻿import React from 'react';
import { Button, IButtonProps } from './Button';
import { IOverlayProps, Overlay } from './Overlay';

interface IProps extends
	IButtonProps,
	IOverlayProps
{
	
}

export const OverlayButton = (
	props: IProps,
) => {
	let p = { ...props };
	if (p.disabled === undefined) {
		p.disabled = false;
	}
	if (p.disabled) {
		const suffix = 'disabled';
		if (p.className) {
			p.className += ' ' + suffix;
		}
		else {
			p.className = suffix;
		}
	}
	return (
		<Button {...p} >
			<Overlay {...p} />
		</Button>
	);
};
